// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx7LCHXmDAaYECUG5a5JlY9vr9NJ_uxUk',
    appId: '1:277633894530:web:89b232deaa952bd3300c9b',
    messagingSenderId: '277633894530',
    projectId: 'final-project-flutter-58670',
    authDomain: 'final-project-flutter-58670.firebaseapp.com',
    storageBucket: 'final-project-flutter-58670.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNBUks0rLLFlTIAN1Z93gP9i0HAv-mxdo',
    appId: '1:277633894530:android:0d6d59b3bb700f8e300c9b',
    messagingSenderId: '277633894530',
    projectId: 'final-project-flutter-58670',
    storageBucket: 'final-project-flutter-58670.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3dq5OwfAD3YE8wdIs2OTnrTRvVw-BqP0',
    appId: '1:277633894530:ios:3b33af93b63edab9300c9b',
    messagingSenderId: '277633894530',
    projectId: 'final-project-flutter-58670',
    storageBucket: 'final-project-flutter-58670.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3dq5OwfAD3YE8wdIs2OTnrTRvVw-BqP0',
    appId: '1:277633894530:ios:3b33af93b63edab9300c9b',
    messagingSenderId: '277633894530',
    projectId: 'final-project-flutter-58670',
    storageBucket: 'final-project-flutter-58670.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx7LCHXmDAaYECUG5a5JlY9vr9NJ_uxUk',
    appId: '1:277633894530:web:4b28856f4cb7ef94300c9b',
    messagingSenderId: '277633894530',
    projectId: 'final-project-flutter-58670',
    authDomain: 'final-project-flutter-58670.firebaseapp.com',
    storageBucket: 'final-project-flutter-58670.firebasestorage.app',
  );
}
